# exercise 1

In [4]:
import numpy as np

In [11]:
err=np.zeros(10)
err[4]=1
print(err)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [12]:
print('ex2')
err=np.arange(10,49)
err

ex2


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [18]:
print('ex3')
err=np.arange(49,9,-1)
err


ex3


array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [22]:
print('ex4')
err=np.arange(9).reshape(3,3)
err


ex4


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [23]:
print('ex5')
err=np.array([1,2,0,0,4,0])
nn=np.nonzero(err)
print(nn)


ex5
(array([0, 1, 4]),)


In [25]:
print('ex6')
err=np.eye(3)
err

ex6


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
print('ex7')
err=np.random.rand(3,3)
minn=np.min(err)
maxx=np.max(err)
print(err)
print(f'min:{minn}')
print(f'max:{maxx}')


ex7
[[0.62397848 0.12197093 0.15797614]
 [0.59579004 0.0296952  0.43658005]
 [0.22670585 0.73925046 0.05709339]]
min:0.02969520144721627
max:0.7392504553800701


In [31]:
print('ex8')
err=np.random.rand(5,5)
minn=np.min(err)
maxx=np.max(err)
print(err)
print(f'min:{minn}')
print(f'max:{maxx}')

ex8
[[0.82021414 0.55711069 0.61360109 0.07991351 0.35565645]
 [0.42475381 0.18432699 0.40877756 0.39200172 0.24824463]
 [0.00832002 0.60494415 0.6972536  0.97541548 0.54919624]
 [0.86758044 0.39252229 0.82990163 0.89103124 0.40123167]
 [0.89609233 0.4674008  0.35800948 0.62873596 0.81843397]]
min:0.00832002490871886
max:0.9754154848866814


In [32]:
print('ex9')
array=np.array([1,3,5,11,15,20,25])
target=14
index=np.argmin(np.abs(array-target))
bb=array[index]
print(f'the closest value to {target} is {bb}')

ex9
the closest value to 14 is 15


In [36]:
print('ex10')
array=np.array([[5,9,3],[10,2,15],[6,7,8]])
maxx=np.argmax(array,axis=1)
array[np.arange(array.shape[0]),maxx]=0
print('array after replacing the maximum element in each row with 0: ')
print(array)

ex10
array after replacing the maximum element in each row with 0: 
[[ 5  0  3]
 [10  2  0]
 [ 6  7  0]]


In [ ]:
print('ex11')
array=np.array([2,3,2,5,8,3,3,7,2,3,5,5,5,5])
values,counts=np.unique(array,return_counts=True)
most=values[np.argmax(counts)]
print(f'the most common value:{most}')

In [37]:
print('ex12')
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
res=np.dot(array,array.T)
res=array@array.T
print(res)

ex12
[[ 14  32  50]
 [ 32  77 122]
 [ 50 122 194]]


In [39]:
print('ex13')
matrix = np.array([[6, 1, 1], [4, -2, 5], [2, 8, 7]])
deter=np.linalg.det(matrix)
print(f'determinant of the matrix is {deter}')

ex13
determinant of the matrix is -306.0


In [40]:
print('ex14')
matrix = np.array([[1, 2, 3], [0, 1, 4], [5, 6, 0]])
det = np.linalg.det(matrix)
if det != 0:
    matrix_inverse = np.linalg.inv(matrix)
    print("Inverse of the matrix:")
    print(matrix_inverse)
else:
    print("The matrix is singular and does not have an inverse.")


ex14
Inverse of the matrix:
[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]
